#!/bin/bash
# generated by Gemini Diffusion
# 2025-06-23

# --- Configuration ---
IMAGE_FOLDER=$1  # Use first arg for image folder

FILENAME_PREFIX=$2 # Use second arg for filename prefix

LMSERVER_URL="http://localhost:1234/v1/chat/completions" # Replace if your LMStudio server URL is different

MODEL_NAME="qwen3-vl-8b-instruct" # Replace with the specific model name you are using in LMStudio

PROMPT_PREFIX="Hi Qwen, please read the 'Plate' text from the label. The text should consist of a one digit number, one uppercase letter, and another one digit number. Print only this text. Thanks!" # The base prompt to send with each image


# --- Input Validation ---
# Check if the image folder exists
if [ ! -d "$IMAGE_FOLDER" ]; then
    echo "Error: Image folder '$IMAGE_FOLDER' not found."
    exit 1
fi

# Check if curl is installed
if ! command -v curl &> /dev/null; then
    echo "Error: 'curl' command not found. Please install curl."
    exit 1
fi

# Check if jq is installed (for parsing JSON response)
if ! command -v jq &> /dev/null; then
    echo "Error: 'jq' command not found. Please install jq."
    exit 1
fi

# --- Main Script ---
echo "Processing images in '$IMAGE_FOLDER'..."

# Loop through all image files in the folder (adjust extensions as needed)
find "$IMAGE_FOLDER" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.jpeg" \) | while read -r IMAGE_PATH; do

    # Check if the file is readable
    if [ -r "$IMAGE_PATH" ]; then
        # Get the filename without path and extension
        FILENAME=$(basename -- "$IMAGE_PATH")
        FILENAME_NO_EXT="${FILENAME%.*}"
        EXTENSION="${FILENAME##*.}"

        echo "Processing image: $FILENAME"

        # Encode the image to base64
        BASE64_IMAGE=$(base64 "$IMAGE_PATH")

        # Create a temporary file for the JSON payload

        TEMP_PAYLOAD_FILE=$(mktemp)
        if [ -z "$TEMP_PAYLOAD_FILE" ]; then
            echo "Error: Failed to create temporary file."
            continue # Skip to the next image
        fi

        # Construct the JSON payload for the LMStudio API
        # Note: The exact structure might vary slightly depending on the LMStudio version and model configuration.
        # This is a common structure for chat models with image support.


        PAYLOAD=$(cat <<EOF  > "$TEMP_PAYLOAD_FILE"
{
  "model": "$MODEL_NAME",
  "messages": [
    {
      "role": "user",
      "content": [
        {
          "type": "input_text",
          "text": "$PROMPT_PREFIX"
        },
        {
          "type": "input_image",
          "image_url": {
            "url": "data:image/jpeg;base64,$BASE64_IMAGE"
          }
        }
      ]
    }
  ],
  "max_tokens": -1,
  "temperature": 0.7,
  "stream": false
}
EOF
)

### example curl command from LMStudio
# curl http://localhost:1234/v1/chat/completions \
#   -H "Content-Type: application/json" \
#   -d '{
#     "model": "google/gemma-3-12b",
#     "messages": [
#       { "role": "system", "content": "Always answer in rhymes. Today is Thursday" },
#       { "role": "user", "content": "What day is it today?" }
#     ],
#     "temperature": 0.7,
#     "max_tokens": -1,
#     "stream": false
# }'
        echo $PAYLOAD

        # Send the request to the LMStudio server using curl with the temporary file
        RESPONSE=$(curl -s -X POST $LMSERVER_URL \
             -H "Content-Type: application/json" \
             -d "@$TEMP_PAYLOAD_FILE")

        # Clean up the temporary file
        rm "$TEMP_PAYLOAD_FILE"

        # Check if the curl command was successful
        if [ $? -ne 0 ]; then
            echo "Error: Failed to connect to LMStudio server for $FILENAME."
            continue # Skip to the next image
        fi

        # Extract the generated text from the JSON response using jq
        # The jq path might need adjustment based on the exact response structure
        QUERY_RESULT=$(echo "$RESPONSE" | jq -r '.choices[0].message.content')

        # Check if jq was successful and if a result was obtained
        if [ $? -ne 0 ] || [ "$QUERY_RESULT" == "null" ]; then
            echo "Error: Failed to extract result from response for $FILENAME."
            echo "Raw Response: $RESPONSE"
            continue # Skip to the next image
        fi

        # Sanitize the query result for use as a filename
        # Remove characters that are typically problematic in filenames
        SANITIZED_RESULT=$(echo "$QUERY_RESULT" | sed 's/[^a-zA-Z0-9_.-]/_/g' | sed 's/_\+_//g' | sed 's/^_//' | sed 's/_$//')

        # Check if the sanitized result is not empty
        if [ -z "$SANITIZED_RESULT" ]; then
            echo "Warning: Sanitized query result for $FILENAME is empty. Skipping rename."
            continue # Skip to the next image
        fi

        # Construct the new filename
        NEW_FILENAME="${FILENAME_PREFIX}${SANITIZED_RESULT}.${EXTENSION}"
        NEW_IMAGE_PATH="${IMAGE_FOLDER}/${NEW_FILENAME}"

        # Check if the new filename already exists
        if [ -e "$NEW_IMAGE_PATH" ]; then
            echo "Warning: New filename '$NEW_FILENAME' already exists. Skipping rename for '$FILENAME'."
            continue # Skip to the next image
        fi

        # Rename the file
        echo "Renaming '$FILENAME' to '$NEW_FILENAME'"
        mv "$IMAGE_PATH" "$NEW_IMAGE_PATH"

        # Check if the rename was successful
        if [ $? -ne 0 ]; then
            echo "Error: Failed to rename '$FILENAME' to '$NEW_FILENAME'."
        fi

    else
        echo "Warning: Skipping unreadable file: $FILENAME"
    fi
done

echo "Processing complete."
